### ISSUE TITLE
Tinkers Con Capacitor Modifier

### ISSUE THREAD

**Issue by NeosGhost** [RCXcrafter/Materialis#17]
Enigmatica 6 (expert): 0.5.24
Forge: 36.2.22
Tcon:3.3.2.324 
Materialis: 1.16.5-2.4.2

Having an issue with the capacitor modifiers 
![qrei0Kb 1](https://user-images.githubusercontent.com/16095247/151281638-20448d7f-61c9-4e1e-ae5b-53bc0da5e8c8.jpeg)

tool does not seem to use RF just durability
![wZKQLAM - Imgur](https://user-images.githubusercontent.com/16095247/151281734-61f34837-72d4-4551-84c0-13e3874d905b.jpg)

Thanks

**Comment by MuteTiefling** [comment]
A response from the Materials dev would be helpful, but I believe this is meant for tools that already _use_ FE. Not to add FE usage to tools that normally use durability:

![image](https://user-images.githubusercontent.com/9543430/151388814-fd7ffb54-b633-4cf9-a6fa-bc748b6ea8fb.png)

Since we don't have Draconic, we might be missing some other modifiers that would make this make more sense.

**Comment by RCXcrafter** [comment]
materialis 2.5.0 has been released, redstone arsenal compatibility was added and the capacitor modifier is only enabled if draconic evolution or redstone arsenal is installed.

**Comment by MuteTiefling** [comment]
Awesome, thanks!
