### ISSUE TITLE
[1.18.2] New update Fails to join world

### ISSUE THREAD

**Issue by ffuentesm** [RCXcrafter/Materialis#18]
When I try to join a world or create a new world, the game fails to place the player on it. 
Nothing wrong happens if I disable Materialis 

Materialis: [materialis-1.18.2-2.5.2.jar](https://www.curseforge.com/minecraft/mc-mods/materialis/files/3785045)
Tinkers: TConstruct-1.18.2-3.5.0.17.jar
Mantle: Mantle-1.18.2-1.9.20.jar
Forge: 40.1.19
[2022-05-09-4.log](https://github.com/RCXcrafter/Materialis/files/8651457/2022-05-09-4.log)

**Comment by RCXcrafter** [comment]
Apparently by registering a tag for an ore that doesn't exist I accidentally uncovered a weird interaction between immersive engineering, jaopca and quark. Since I'm not currently using this tag I have removed it as a temporary fix however I will leave this issue open until the underlying issue is fixed.

**Comment by RCXcrafter** [comment]
Closing this since jaopca no longer adds recipes with empty outputs
