### ISSUE TITLE
Shadow Steel and Refined Radiance are no longer in Create

### ISSUE THREAD

**Issue by definitelynotrazu** [RCXcrafter/Materialis#22]
As of recent 1.16+ updates, create has removed refined radiance and shadow steel. Making them unattainable and deprecated. I'm assuming them still being a material is unintentional

**Comment by RCXcrafter** [comment]
That was more or less intentional but I can see why you'd think it isn't, in materialis 1.18.2-2.7.0 the recipe for chromatic compound will be added back with a config to turn it off and a config to turn the materials off.
https://github.com/RCXcrafter/Materialis/commit/334d29a7704863b99b19cd888a14ba0d017c768e
